KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
    user_admin="admin-secret"
    user_bob="bob-secret";
  org.apache.kafka.common.security.scram.ScramLoginModule required;
};
